#!/usr/bin/env python3
"""S38 root-tracking round (docs/S38_ROOT_TRACKING_VERDICT.md): write every arm's config from its parent.

Same contract as `tools/rt/make_configs.py`: each arm is its parent plus the listed overrides and
nothing else, so an arm differs from its control exactly where the table below says. Parents are the
x1001 recipe configs (`configs/x1001/x1001_s37.yaml`: S37 routed readout, the fixed baseline;
`configs/x1001/x1001_e7.yaml`: S37's graph with an absolute 51D head, the encoder control). The split
is the fixed protocol's `splits_semkine.json`. `_2k` arms are the screening budget (the cosine
compressed to 2000 steps).

The two factors of the round:
  encoder           S37 event graph (`event_gnn`)  vs  sparse pyramid (`sparse_pyramid`, SP)
  root measurement  S37 delta (`ROOT_MEAS: delta`)  vs  absolute + constant-gain filter (M1:
                    `ROOT_MEAS: abs`, `ROOT_REF`, `ROOT_FILTER_GAIN: 0.5`, `LOSS.ROOT_LOSS: chordal`)

`ROOT_REF` is the mean root rotation of the *training* split (chordal mean over the 50 ms protocol
steps of every valid run); no development or test sequence enters it. The filter gain 0.5 is fixed
a priori (the geodesic midpoint; docs/ARCHITECTURE_DECISION.md section 3.1 registered 0.5 as the prior) and
is not tuned on zgz.

    python tools/s38/make_configs.py            # (re)writes configs/s38/*.yaml
"""
from __future__ import annotations

import copy
import sys
from pathlib import Path

import numpy as np
import yaml

REPO = Path(__file__).resolve().parents[2]
sys.path[:0] = [str(REPO)]
S37 = REPO / "configs/x1001/x1001_s37.yaml"
E7 = REPO / "configs/x1001/x1001_e7.yaml"
OUT = REPO / "configs/s38"
SCREEN_STEPS = 2000

#: the event-graph knobs a sparse-pyramid arm does not read (dropped, so the config cannot suggest otherwise)
_GNN_ONLY = {"ENCODER_K": None, "ENCODER_MAX_NODES": None, "ENCODER_WINDOW": None, "ENCODER_T_SCALE": None,
             "ENCODER_LAYERS": None}
SP = {"MODEL": {"BACKBONE": "sparse_pyramid", "ENCODER": "sparse_pyramid", "ENCODER_CELL": 4, "ENCODER_CHANNELS": [48, 96, 192],
                "ENCODER_BLOCKS": [1, 2, 2], **_GNN_ONLY}}


def training_root_ref() -> list:
    """Chordal mean of the training split's root rotations at the protocol's 50 ms steps."""
    from scipy.spatial.transform import Rotation
    from semkine.dataset import _read_meta51, sequences_for_split
    cfg = yaml.safe_load(S37.read_text())
    root = Path(cfg["DATA"]["ROOT"])
    aa = []
    for seq, d in sequences_for_split(root, "train", Path(cfg["DATA"]["SPLITS_MANIFEST"])):
        p = _read_meta51(str(root / d / seq) + ".meta")
        runs = np.asarray(np.load(str(root / d / seq) + "_aux.npz", allow_pickle=True)["valid_runs_ms"]).reshape(-1, 2)
        for a, b in runs:
            aa.append(p[np.arange(a + 49, b, 50), 3:6])
    return [round(float(v), 6) for v in Rotation.from_rotvec(np.concatenate(aa).astype(np.float64)).mean().as_rotvec()]


def m1(ref: list) -> dict:
    return {"MODEL": {"ROOT_MEAS": "abs", "ROOT_REF": ref, "ROOT_FILTER_GAIN": 0.5},
            "LOSS": {"ROOT_LOSS": "chordal"}}


def merge(dst: dict, src: dict) -> dict:
    for k, v in src.items():
        if v is None:
            dst.pop(k, None)
        elif isinstance(v, dict):
            merge(dst.setdefault(k, {}), v)
        else:
            dst[k] = v
    return dst


def arms(ref: list) -> dict:
    """name -> (parent, overrides, why)."""
    return {
        "s38_s37abs": (S37, m1(ref), "S37 event graph + M1 root (absolute, reference-relative, chordal, gain 0.5)"),
        "s38_spdelta": (S37, SP, "sparse pyramid encoder + S37 delta root (routed readout unchanged)"),
        "s38_spabs": (S37, merge(copy.deepcopy(SP), m1(ref)), "sparse pyramid encoder + M1 root"),
        "s38_spe7": (E7, SP, "sparse pyramid with E7's absolute 51D head, no prev (encoder control vs rt_e7)"),
    }


def write(name: str, parent: Path, over: dict, why: str, steps=None) -> Path:
    cfg = merge(copy.deepcopy(yaml.safe_load(parent.read_text())), copy.deepcopy(over))
    run = name if steps is None else f"{name}_2k"
    if steps is not None:
        cfg["TRAIN"]["MAX_STEPS"] = steps
    cfg["TRAIN"]["OUTPUT_DIR"] = f"outputs/semkine/{run}"
    cfg["TRAIN"]["RUN_NAME"] = run
    cfg["EVAL"]["OUTPUT_DIR"] = f"outputs/semkine/{run}/eval"
    head = (f"# {run}: {why}.\n# Generated by tools/s38/make_configs.py from {parent.relative_to(REPO)}"
            f" with {over}" + (f", TRAIN.MAX_STEPS {steps} (screening budget)" if steps else "") + ".\n"
            "# Seeds and output paths are set on the command line.\n")
    p = OUT / f"{run}.yaml"
    p.write_text(head + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True))
    return p


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    ref = training_root_ref()
    print("ROOT_REF (training split mean root, axis-angle):", ref)
    for name, (parent, over, why) in arms(ref).items():
        print(write(name, parent, over, why).relative_to(REPO))
        print(write(name, parent, over, why, SCREEN_STEPS).relative_to(REPO))


if __name__ == "__main__":
    main()
